CREATE TABLE IF NOT EXISTS table_persons
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    TEXT    NOT NULL CHECK ( length(first_name) > 0 ),
    patronymic    TEXT,
    last_name     TEXT    NOT NULL CHECK ( length(last_name) > 0 ),
    date_of_birth DATE    NOT NULL,
    is_deleted    BOOLEAN NOT NULL

);