CREATE TABLE IF NOT EXISTS table_products
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name        TEXT           NOT NULL CHECK ( length(name) > 0 ),
    description TEXT           NOT NULL CHECK ( length(description) > 0),
    price       NUMERIC(19, 4) NOT NULL CHECK ( price > 0 )

);


