CREATE TABLE IF NOT EXISTS table_sales
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER     NOT NULL,
    sale_date TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT foreign_key_person_id
        FOREIGN KEY (person_id) REFERENCES table_persons (id) ON DELETE NO ACTION
);