CREATE TABLE IF NOT EXISTS table_warehouses
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        INTEGER UNIQUE NOT NULL,
    quantity_in_stock INTEGER NOT NULL CHECK ( quantity_in_stock >= 0 ),

    CONSTRAINT foreign_key
        FOREIGN KEY (product_id) REFERENCES table_products (id) ON DELETE NO ACTION
);



CREATE OR REPLACE FUNCTION fn_reduce_stock_after_sale()
    RETURNS TRIGGER AS
$$
DECLARE
    current_stock INTEGER;
BEGIN
    SELECT quantity_in_stock
    INTO current_stock
    FROM table_warehouses
    WHERE product_id = NEW.product_id;

    IF current_stock < NEW.quantity OR NEW.quantity <= 0 THEN
        RAISE EXCEPTION 'Недостаточно товара в ( в наличие: %) или некоректное количество (%)',
            current_stock, NEW.quantity;
    END IF;

    UPDATE table_warehouses
    SET quantity_in_stock = quantity_in_stock - NEW.quantity
    WHERE product_id = NEW.product_id;

    RETURN NEW;
END
$$ LANGUAGE plpgsql;


DROP TRIGGER IF EXISTS trg_on_product_sold ON table_sales_item;
CREATE TRIGGER trg_on_product_sold
    AFTER INSERT
    ON table_sales_item
    FOR EACH ROW
EXECUTE FUNCTION fn_reduce_stock_after_sale();
